### ISSUE TITLE
Check to see if ELLIE Model can create/submit during a process on main thread

### ISSUE THREAD

**Issue by cjones2500** [snoplus/orca-snoplus#8]
Currently, the ELLIE model will submit to the couchDB on the main thread (I think). Whilst the ELLIE custom run GUI doesn't need to be accessible during a run. It may be a good idea to check the response from this during a run

**Comment by fbdescamps** [comment]
@EdLeming Please confirm that this issue is no longer relevant and close.

**Comment by EdLeming** [comment]
@fbdescamps This issue is resolved. I don't have permissions to close myself
